sudo: required
services:
  - docker
language: python
python:
  - "3.6"
install:
  - pip3 install git+https://github.com/nextstrain/cli
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
script:
  - mkdir -p data/
  - cp -v example_data/h5n1_ha.fasta data/h5n1_ha.fasta
  - nextstrain build . auspice/flu_avian_h5n1_ha_tree.json
